basePath: /book
definitions:
  domain.Book:
    properties:
      author:
        type: string
      count:
        type: integer
      id:
        type: integer
      publisher:
        type: string
      title:
        type: string
      year:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: REST API for Books App
  title: Books API
  version: "1.0"
paths:
  /{id}:
    get:
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Book'
        "204":
          description: No such book
          schema:
            type: header
        "400":
          description: Incorrect request
          schema:
            type: header
        "404":
          description: Page not found
          schema:
            type: header
      summary: Get book from database
  /add:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Add book in database
swagger: "2.0"
